baseurl = "http://blog.fragmentof.net/"
languageCode = "ja-jp"
title = "FRAGMENT"
theme = "blog-fragment"
isCJKLanguage = true

[params]
twitter = "ish1r0k1"
github = "ish1r0k1"
email = "ishiwatari@fragmentof.net"
googleAnalytics = "UA-79199286-3"

[author]
  name = "Hiroki Ishiwatari"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."
